### PR TITLE
Add x86 files form leaked Lenovo Tab S8 5.0.1 ROM

### PR DESCRIPTION
**Pull request by balika011**

### CODE REVIEW

**Comment by jrizzoli** [comment]
Thanks I'll dload this and push these files on squashed may commit (I'll give u credits ofc) ;)

**Comment by jrizzoli** [comment]
would u mind send me system/app gapps too?

**Comment by balika011** [comment]
Is there any more?

**Comment by jrizzoli** [comment]
Nope. I just need *sync stuffs. Will merge those too. Thanks

**Comment by jrizzoli** [comment]
Missing GMS (Play services)

**Comment by jrizzoli** [comment]
Nevermind, found one on xda, thanks for files

**Pull request closed without merging**
